### ISSUE TITLE
Can I optimize with admm in GPU？

### ISSUE THREAD

**Issue by xingyuezhiji** [bhushan23/ADMM#1]

**Comment by bhushan23** [comment]
You can.
Approach will be to solve independent problems on different GPUs and then combine.
If one has two GPUs using SLI
vs 
two PCs each with one GPU
later is preferred for ADMM where one can leverage full GPU for solving one problem that machine is working on.

**Comment by xingyuezhiji** [comment]
@bhushan23 Thanks a lot!
